POST http://localhost:6000/users
Content-Type: application/json

{
   "name":"Samuel Ndambuki",
   "email":"sam.ndambuki08@gmail.com",
   "password":"N10234424008s"
}


###
POST http://localhost:6000/users/reset-password


###
GET http://localhost:6000/users/searchUsersByName
